# Generated by Django 2.1.3 on 2019-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cds_Fleet',
            fields=[
                ('airline', models.CharField(max_length=10)),
                ('tailsign', models.CharField(max_length=10)),
                ('ac_type', models.CharField(max_length=10)),
                ('wisp', models.CharField(max_length=10)),
                ('wisp_status', models.CharField(blank=True, max_length=10, null=True)),
                ('vlan', models.CharField(max_length=10)),
                ('bc_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ant_type', models.CharField(blank=True, max_length=10, null=True)),
                ('wap_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_status', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_eis_date', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_xid', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_ip', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_status', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_eis_date', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_xid', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_ip', models.CharField(blank=True, max_length=10, null=True)),
                ('xid_reported', models.CharField(blank=True, max_length=10, null=True)),
                ('map_lbp', models.CharField(blank=True, max_length=50, null=True)),
                ('map_reported', models.CharField(blank=True, max_length=50, null=True)),
                ('optfile_reported', models.CharField(blank=True, max_length=50, null=True)),
                ('gcs_mdm_version', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_time', models.CharField(blank=True, max_length=50, null=True)),
                ('bcsla_patch', models.CharField(blank=True, max_length=50, null=True)),
                ('whitelist_version', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cds_fleet',
            },
        ),
        migrations.CreateModel(
            name='Cds_Fleet_bak',
            fields=[
                ('airline', models.CharField(max_length=10)),
                ('tailsign', models.CharField(max_length=10)),
                ('ac_type', models.CharField(max_length=10)),
                ('wisp', models.CharField(max_length=10)),
                ('wisp_status', models.CharField(blank=True, max_length=10, null=True)),
                ('vlan', models.CharField(max_length=10)),
                ('bc_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ant_type', models.CharField(blank=True, max_length=10, null=True)),
                ('wap_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_status', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_eis_date', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_xid', models.CharField(blank=True, max_length=10, null=True)),
                ('gen1_ip', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_status', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_eis_date', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_xid', models.CharField(blank=True, max_length=10, null=True)),
                ('gen3_ip', models.CharField(blank=True, max_length=10, null=True)),
                ('xid_reported', models.CharField(blank=True, max_length=10, null=True)),
                ('map_lbp', models.CharField(blank=True, max_length=50, null=True)),
                ('map_reported', models.CharField(blank=True, max_length=50, null=True)),
                ('optfile_reported', models.CharField(blank=True, max_length=50, null=True)),
                ('gcs_mdm_version', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_time', models.CharField(blank=True, max_length=50, null=True)),
                ('bcsla_patch', models.CharField(blank=True, max_length=50, null=True)),
                ('whitelist_version', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cds_fleet_bak',
            },
        ),
    ]
