# Generated by Django 2.1.3 on 2019-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DartOpsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10)),
                ('aircraft', models.CharField(max_length=10)),
                ('aircraft_type', models.CharField(max_length=10)),
                ('flight_type', models.CharField(max_length=20)),
                ('antenna_type', models.CharField(max_length=10)),
                ('xid', models.CharField(max_length=10)),
                ('bc_gen', models.CharField(max_length=10)),
                ('flight_id', models.CharField(max_length=10)),
                ('flight_num', models.CharField(default='0000', max_length=10)),
                ('excluded', models.BooleanField()),
                ('exclusion_reason', models.CharField(max_length=10, null=True)),
                ('departure_airport', models.CharField(max_length=10, null=True)),
                ('arrival_airport', models.CharField(max_length=10, null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('flight_time', models.IntegerField(null=True)),
                ('connected_sec', models.IntegerField(null=True)),
                ('connected_sec_expected', models.IntegerField(null=True)),
                ('avail_raw', models.IntegerField(null=True)),
                ('avail_calibrated', models.IntegerField(null=True)),
                ('latency', models.FloatField(null=True)),
                ('latency_std', models.FloatField(null=True)),
                ('packet_loss', models.FloatField(null=True)),
                ('packet_loss_std', models.FloatField(null=True)),
                ('beam_switch_count', models.IntegerField(null=True)),
                ('beam_switch_average_sec', models.IntegerField(null=True)),
                ('beam_switch_excluded_sec', models.IntegerField(null=True)),
                ('kbpu', models.FloatField(null=True)),
                ('device_count', models.IntegerField(null=True)),
                ('spare_field1', models.CharField(max_length=10, null=True)),
                ('spare_field2', models.CharField(max_length=10, null=True)),
                ('spare_field3', models.CharField(max_length=10, null=True)),
                ('spare_field4', models.CharField(max_length=10, null=True)),
                ('spare_field5', models.CharField(max_length=10, null=True)),
                ('spare_field6', models.CharField(max_length=10, null=True)),
                ('spare_field7', models.CharField(max_length=10, null=True)),
                ('spare_field8', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'dart_ops_report',
                'db_table': 'dart_ops_report',
            },
        ),
    ]
