# Generated by Django 2.1.3 on 2019-08-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dartopsreport',
            options={'managed': True, 'verbose_name': 'dart_ops_report'},
        ),
    ]
