# Generated by Django 2.1.3 on 2019-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_auto_20190803_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartopsreport',
            name='flight_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
