# Generated by Django 2.1.3 on 2019-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0003_auto_20190804_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartopsreport',
            name='exclusion_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
