# Generated by Django 2.1.3 on 2019-08-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0004_auto_20190804_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartopsreport',
            name='aircraft',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='aircraft_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='antenna_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='arrival_airport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='bc_gen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='departure_airport',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='flight_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='flight_num',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='flight_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='operator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='xid',
            field=models.CharField(max_length=20),
        ),
    ]
