# Generated by Django 2.1.3 on 2019-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0005_auto_20190804_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dartopsreport',
            name='spare_field1',
        ),
        migrations.AddField(
            model_name='dartopsreport',
            name='generated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='avail_calibrated',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='avail_raw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='flight_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dartopsreport',
            name='xid',
            field=models.IntegerField(null=True),
        ),
    ]
