# Generated by Django 2.2.4 on 2019-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0006_auto_20190804_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartopsreport',
            name='excluded',
            field=models.IntegerField(),
        ),
    ]
